// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Claims.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Claims.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20260723042550_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("claims")
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("booking_number");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int?>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("Product")
                        .HasColumnType("text")
                        .HasColumnName("product");

                    b.Property<int?>("SalesChannel")
                        .HasColumnType("integer")
                        .HasColumnName("sales_channel");

                    b.Property<int?>("Service")
                        .HasColumnType("integer")
                        .HasColumnName("service");

                    b.Property<bool?>("Skissim")
                        .HasColumnType("boolean")
                        .HasColumnName("skissim");

                    b.Property<int?>("SkissimType")
                        .HasColumnType("integer")
                        .HasColumnName("skissim_type");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customer_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_bookings_supplier_id");

                    b.ToTable("bookings", "claims");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("ClaimSummary")
                        .HasColumnType("text")
                        .HasColumnName("claim_summary");

                    b.Property<string>("CustomerSuppInfo")
                        .HasColumnType("text")
                        .HasColumnName("customer_supp_info");

                    b.Property<string>("FollowedBy")
                        .HasColumnType("text")
                        .HasColumnName("followed_by");

                    b.Property<string>("PurposeOfSolution")
                        .HasColumnType("text")
                        .HasColumnName("purpose_of_solution");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int?>("Solution")
                        .HasColumnType("integer")
                        .HasColumnName("solution");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("SupplierSuppInfo")
                        .HasColumnType("text")
                        .HasColumnName("supplier_supp_info");

                    b.Property<string>("UpdateReason")
                        .HasColumnType("text")
                        .HasColumnName("update_reason");

                    b.HasKey("Id")
                        .HasName("pk_claims");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_claims_booking_id");

                    b.ToTable("claims", "claims");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.ClaimDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset?>("DateEndOfFollowUp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end_of_follow_up");

                    b.Property<DateTimeOffset?>("DateLastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_update");

                    b.Property<DateTimeOffset?>("DateOfArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_arrival");

                    b.Property<DateTimeOffset?>("DateOfDeparture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_departure");

                    b.Property<DateTimeOffset?>("DateOfReceivedClaim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_received_claim");

                    b.Property<DateTimeOffset?>("DateOfStartFollowUp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_start_follow_up");

                    b.HasKey("Id")
                        .HasName("pk_claim_dates");

                    b.HasIndex("ClaimId")
                        .IsUnique()
                        .HasDatabaseName("ix_claim_dates_claim_id");

                    b.HasIndex("DateOfReceivedClaim")
                        .HasDatabaseName("ix_claim_dates_date_of_received_claim");

                    b.ToTable("claim_dates", "claims");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Compensation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<float?>("ClaimRefund")
                        .HasColumnType("real")
                        .HasColumnName("claim_refund");

                    b.Property<float?>("CustomerUsedVoucher")
                        .HasColumnType("real")
                        .HasColumnName("customer_used_voucher");

                    b.Property<float?>("CustomerVoucher")
                        .HasColumnType("real")
                        .HasColumnName("customer_voucher");

                    b.Property<int?>("RefundState")
                        .HasColumnType("integer")
                        .HasColumnName("refund_state");

                    b.Property<float?>("SupplierRefund")
                        .HasColumnType("real")
                        .HasColumnName("supplier_refund");

                    b.HasKey("Id")
                        .HasName("pk_compensations");

                    b.HasIndex("ClaimId")
                        .IsUnique()
                        .HasDatabaseName("ix_compensations_claim_id");

                    b.ToTable("compensations", "claims");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AkioNumber")
                        .HasColumnType("integer")
                        .HasColumnName("akio_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", "claims");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SupplierAkioNumber")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_akio_number");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", "claims");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "claims");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Modules.Claims.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_customers_customer_id");

                    b.HasOne("Modules.Claims.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Bookings")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_suppliers_supplier_id");

                    b.Navigation("Customer");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Claim", b =>
                {
                    b.HasOne("Modules.Claims.Domain.Entities.Booking", "Booking")
                        .WithOne("Claim")
                        .HasForeignKey("Modules.Claims.Domain.Entities.Claim", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claims_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.ClaimDate", b =>
                {
                    b.HasOne("Modules.Claims.Domain.Entities.Claim", "Claim")
                        .WithOne("ClaimDate")
                        .HasForeignKey("Modules.Claims.Domain.Entities.ClaimDate", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claim_dates_claims_claim_id");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Compensation", b =>
                {
                    b.HasOne("Modules.Claims.Domain.Entities.Claim", "Claim")
                        .WithOne("Compensation")
                        .HasForeignKey("Modules.Claims.Domain.Entities.Compensation", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compensations_claims_claim_id");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Claim", b =>
                {
                    b.Navigation("ClaimDate")
                        .IsRequired();

                    b.Navigation("Compensation")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Modules.Claims.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
